<?php

// autoload_psr4.php @generated by Composer

$assetDir = dirname(dirname(__FILE__));
$baseDir = dirname($assetDir);

return array(
    'PHPMailer\\PHPMailer\\' => array($assetDir . '/phpmailer/phpmailer/src'),
);
