<?php

// autoload_classmap.php @generated by Composer

$assetDir = dirname(dirname(__FILE__));
$baseDir = dirname($assetDir);

return array(
    'PHPMailer\\PHPMailer\\Exception' => $assetDir . '/phpmailer/phpmailer/src/Exception.php',
    'PHPMailer\\PHPMailer\\OAuth' => $assetDir . '/phpmailer/phpmailer/src/OAuth.php',
    'PHPMailer\\PHPMailer\\PHPMailer' => $assetDir . '/phpmailer/phpmailer/src/PHPMailer.php',
    'PHPMailer\\PHPMailer\\POP3' => $assetDir . '/phpmailer/phpmailer/src/POP3.php',
    'PHPMailer\\PHPMailer\\SMTP' => $assetDir . '/phpmailer/phpmailer/src/SMTP.php',
    'upload' => $assetDir . '/verot/class.upload.php/src/class.upload.php',
);
